name: realworld_module_frameshot
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  # Riverpod
  hooks_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  # Image
  cached_network_image: ^3.2.3
  bitmap: ^0.1.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  camera: ^0.10.5+2
  permission_handler: ^10.4.2
  event_listener: ^0.2.0
  gap: ^3.0.1
  flutter_native_image: ^0.0.6+1
  gallery_saver: ^2.3.2
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  riverpod_generator: ^2.2.3
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  network_image_mock: ^2.1.1
  mocktail: ^0.3.0
  build_runner: ^2.4.6

flutter:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg